# Site settings
title: Openinx Blog
email: openinx@gmail.com
description: "To be a great hacker."
baseurl: ""
url: "http://xuzuguang.men/"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

permalink: pretty

